### PR TITLE
chore: upgrade to Go 1.20

### PR DESCRIPTION
**Pull request by mojixcoder**

### CODE REVIEW

**Review by jogly — APPROVED** [review]
nice!

**Comment by jogly** [comment]
could you also upgrade golangci lint to a recent version that works with 1.20+?

**Review by isaacbrodsky — DISMISSED** [review]

**Review by isaacbrodsky — APPROVED** [review]

**Comment by mojixcoder** [comment]
After running lints locally, it should return success status code now.

**Comment by mojixcoder** [comment]
Removed linters are the ones that either got removed or replaced by other linters in the `golangci` new versions.

**Review by jogly — APPROVED** [review]

**Pull request merged**
